# es2020.symbol.wellknown.tpld.toml
tpl-spec = "0.1.0"
from = "ts"
to = "zh_CN"

type = "lib"
# lib.es2020.symbol.wellknown.d.ts

dep = [
  "./es2015.iterable",
  "./es2015.symbol",
]


[[d]]
scope = "SymbolConstructor"
to = "符号构造器"
[d.d]
matchAll = "匹配全"

#RegExp
