# es2020.tpld.toml
tpl-spec = "0.1.0"
from = "ts"
to = "zh_CN"

type = "lib"
# lib.es2020.d.ts

dep = [
  "./es2019",
  "./es2020.bigint",
  "./es2020.promise",
  "./es2020.sharedmemory",
  "./es2020.string",
  "./es2020.symbol.wellknown",
  "./intl/es2020.intl",
]
