# es2015.tpld.toml
tpl-spec = "0.1.0"
from = "ts"
to = "zh_CN"

type = "lib"
# lib.es2015.d.ts

dep = [
  "./es5",
  "./es2015.core",
  "./es2015.collection",
  "./es2015.iterable",
  "./es2015.generator",
  "./es2015.promise",
  "./es2015.proxy",
  "./es2015.reflect",
  "./es2015.symbol",
  "./es2015.symbol.wellknown",
]
