# es2015.generator.tpld.toml
tpl-spec = "0.1.0"
from = "ts"
to = "zh_CN"

type = "lib"
# lib.es2015.generator.d.ts

dep = [
  "./es2015.iterable",
]


[[d]]
scope = "Generator"
to = "生成器"
[d.d]
"next()" = "下个()"
"return()" = "返回()"
"throw()" = "扔()"

[[d]]
scope = ["GeneratorFunction", "GeneratorFunctionConstructor"]
to = ["生成器函数", "生成器函数构造器"]
[d.d]
"new()" = "新()"
length = "长度"
name = "名称"
prototype = "原型"
