# es2018.asynciterable.tpld.toml
tpl-spec = "0.1.0"
from = "ts"
to = "zh_CN"

type = "lib"
# lib.es2018.asynciterable.d.ts

dep = [
  "./es2015.symbol",
  "./es2015.iterable",
]


[[d]]
scope = "SymbolConstructor"
to = "符号构造器"
[d.d]
asyncIterator = "异步迭代器"

[[d]]
scope = "AsyncIterator"
to = "异步迭代器"
[d.d]
"next()" = "下个()"
"return()" = "返回()"
"throw()" = "扔()"

[[d]]
scope = "AsyncIterable"
to = "异步可迭代"

[[d]]
scope = "AsyncIterableIterator"
to = "异步可迭代迭代器"
