# es2015.symbol.tpld.toml
tpl-spec = "0.1.0"
from = "ts"
to = "zh_CN"

type = "lib"
# lib.es2015.symbol.d.ts

# 全局
[[d]]
scope = ""
[d.d]
Symbol = "符号类"

[[d]]
scope = "SymbolConstructor"
to = "符号构造器"
[d.d]
prototype = "原型"
"for()" = "全局()"
"keyFor()" = "找全局()"
