# es2019.string.tpld.toml
tpl-spec = "0.1.0"
from = "ts"
to = "zh_CN"

type = "lib"
# lib.es2019.string.d.ts


[[d]]
scope = "String"
to = "字符串"
[d.d]
"trimEnd()" = "修剪尾()"
"trimStart()" = "修剪头()"
"trimLeft()" = "修剪左()"
"trimRight()" = "修剪右()"
