# fs_promises.tpld.toml
tpl-spec = "0.1.0"
from = "ts"
to = "zh_CN"

type = "lib:node"
# fs/promises.d.ts
scope = "module:fs/promises"
scope_to = "许诺"

# 全局
[[d]]
scope = ""
[d.d]
"access()" = "访问()"
"copyFile()" = "复制文件()"
"open()" = "打开()"
"rename()" = "重命名()"
"truncate()" = "截断()"
"rmdir()" = "删目录()"
"rm()" = "删()"
"mkdir()" = "建目录()"
"readdir()" = "读目录()"
"readlink()" = "读链接()"
"symlink()" = "符号链接()"
"lstat()" = "链接取状态()"
"stat()" = "取状态()"
"link()" = "链接()"
"unlink()" = "移除()"
"chmod()" = "改模式()"
"lchmod()" = "链接改模式()"
"lchown()" = "链接改所有者()"
"lutimes()" = "链接改时间()"
"chown()" = "改所有者()"
"utimes()" = "改时间()"
"realpath()" = "真路径()"
"mkdtemp()" = "建临时目录()"
"writeFile()" = "写文件()"
"appendFile()" = "追加文件()"
"readFile()" = "读文件()"
"opendir()" = "打开目录()"
"watch()" = "监视()"
"cp()" = "复制()"

[[d]]
scope = "arg:mkdir:options"
to = "选项"
[d.d]
recursive = "递归"

[[d]]
scope = "arg:readdir:options"
to = "选项"
[d.d]
encoding = "编码"
withFileTypes = "文件类型"

[[d]]
scope = ["arg:lstat:opts", "arg:stat:opts"]
to = "选项"
[d.d]
bigint = "大整数"

[[d]]
scope = "arg:writeFile:options"
to = "选项"
[d.d]
mode = "模式"
flag = "标志"

[[d]]
scope = "arg:readFile:options"
to = "选项"
[d.d]
encoding = "编码"
flag = "标志"

[[d]]
scope = "arg:watch:options"
to = "选项"
[d.d]
encoding = "编码"
buffer = "存储"


[[d]]
scope = "FileChangeInfo"
to = "文件改变信息"
[d.d]
eventType = "事件类型"
filename = "文件名"

[[d]]
scope = "FlagAndOpenMode"
to = "标志和打开模式"
[d.d]
mode = "模式"
flag = "标志"

[[d]]
scope = "FileReadResult"
to = "文件读取结果"
[d.d]
bytesRead = "读字节数"
buffer = "存储"

[[d]]
scope = "FileReadOptions"
to = "文件读取选项"
[d.d]
buffer = "存储"
offset = "偏移"
length = "长度"
position = "位置"

[[d]]
scope = "FileHandle"
to = "文件柄"
[d.d]
fd = "文件描述符"
"appendFile()" = "追加文件()"
"chown()" = "改所有者()"
"chmod()" = "改模式()"
"datasync()" = "数据同步()"
"sync()" = "同步()"
"read()" = "读()"
"readFile()" = "读文件()"
"stat()" = "取状态()"
"truncate()" = "截断()"
"utimes()" = "改时间()"
"writeFile()" = "写文件()"
"write()" = "写()"
"writev()" = "写多()"
"readv()" = "读多()"
"close()" = "关闭()"

[[d]]
# 函数参数类型
scope = "arg:FileHandle.readFile:options"
to = "选项"
[d.d]
encoding = "编码"
flag = "标志"

[[d]]
scope = "arg:FileHandle.stat:opts"
to = "选项"
[d.d]
bigint = "大整数"

[[d]]
# 函数返回值类型
scope = "arg:FileHandle.write:"
[d.d]
bytesWritten = "写字节数"
buffer = "存储"
