# tpld-kotlin-zh.tpld.toml
tpl-spec = "0.1.0"

# Kotlin
from = "kotlin"
# 简体中文 (中国)
to = "zh_CN"

dep = [
  # TODO
]

[[d]]
type = "tpl"
[d.d]
tpl = "替"
filename = "文件名"
file-ext = ".替"

[[d]]
type = "keyword"
[d.d]
as = "作"
"as?" = "作?"
break = "断"
class = "类"
continue = "继续"
do = "干"
else = "另"
false = "假"
for = "为"
fun = "术"
if = "若"
in = "在"
"!in" = "不在"
interface = "接口"
is = "是"
"!is" = "不是"
null = "空"
object = "物"
package = "包"
return = "返回"
super = "超"
this = "这"
throw = "扔"
true = "真"
try = "试"
typealias = "类型别名"
#typeof = "typeof"
val = "常"
var = "令"
when = "匹配"
while = "当"
by = "被"
catch = "捉"
" constructor" = "构造"
delegate = "委托"
dynamic = "动态"
field = "字段"
file = "文件"
finally = "最后"
get = "取"
import = "导入"
init = "初始化"
param = "参"
property = "属性"
receiver = "接收器"
set = "设"
setparam = "设参"
value = "值"
where = "其中"
actual = "实际"
abstract = "抽象"
annotation = "标注"
companion = "伴随"
const = "常量"
crossinline = "交叉内联"
data = "数据"
enum = "枚举"
expect = "期望"
external = "外部"
final = "终"
infix = "中缀"
inline = "内联"
inner = "内"
internal = "内部"
lateinit = "迟初始化"
noinline = "不内联"
open = "开"
operator = "运算符"
out = "出"
override = "重写"
private = "私"
protected = "护"
public = "公"
reified = "具体化"
sealed = "密封"
suspend = "挂起"
tailrec = "尾递归"
vararg = "变参"
#field = "字段"
it = "它"


# TODO
