# tpld-rust-zh.tpld.toml
tpl-spec = "0.1.0"

# Rust
from = "rust"
# 简体中文 (中国)
to = "zh_CN"

dep = [
  # TODO
]

[[d]]
type = "tpl"
[d.d]
tpl = "替"
filename = "文件名"
file-ext = ".替"

[[d]]
type = "keyword"
[d.d]
as = "作"
async = "异步"
await = "待"
break = "断"
const = "常"
continue = "继续"
crate = "箱"
dyn = "动态"
else = "另"
enum = "枚举"
extern = "外部"
false = "假"
fn = "术"
for = "为"
if = "若"
impl = "实现"
in = "在"
let = "令"
loop = "循环"
match = "匹配"
mod = "模块"
move = "移动"
mut = "变"
pub = "公"
ref = "引"
return = "返回"
Self = "自己"
self = "自"
static = "静态"
struct = "结构"
super = "超"
trait = "特质"
true = "真"
type = "类型"
union = "联合"
unsafe = "不安全"
use = "用"
where = "其中"
while = "当"
# 保留的关键字不在此处列出


# TODO
