# tpld-dart-zh.tpld.toml
tpl-spec = "0.1.0"

# Dart
from = "dart"
# 简体中文 (中国)
to = "zh_CN"

dep = [
  # TODO
]

[[d]]
type = "tpl"
[d.d]
tpl = "替"
filename = "文件名"
file-ext = ".替"
# Unicode 标识符 (强行改造)
encode-id = "punycode_{{punycode}}_darthateunicode"

[[d]]
type = "keyword"
[d.d]
abstract = "抽象"
as = "作"
assert = "断言"
async = "异步"
await = "待"
break = "断"
case = "情况"
catch = "捉"
class = "类"
const = "常"
continue = "继续"
covariant = "协变"
default = "默认"
#deferred = "?"
do = "干"
dynamic = "动态"
else = "另"
enum = "枚举"
export = "导出"
extends = "扩展"
extension = "扩"
external = "外部"
factory = "工厂"
false = "假"
final = "终"
finally = "最后"
for = "为"
Function = "函数"
get = "取"
hide = "隐藏"
if = "若"
implements = "实现"
import = "导入"
in = "在"
inout = "入出"
interface = "接口"
is = "是"
late = "迟"
library = "库"
mixin = "混入"
native = "原生"
new = "新"
null = "空"
of = "于"
on = ["开", "上"]
operator = "运算符"
out = "出"
part = "部分"
patch = "修补"
required = "要求"
rethrow = "再扔"
return = "返回"
set = "设"
show = "显"
source = "源"
static = "静态"
super = "超"
switch = "选择"
sync = "同步"
this = "这"
throw = "扔"
true = "真"
try = "试"
typedef = "类型定义"
var = "令"
void = "无"
while = "当"
with = "同"
yield = "产生"


# TODO
