name: NPM 发布
on:
  release:
    types: [created]

env:
  # npm pack
  PACK_FILENAME: tpl-ol-doc-0.1.0-a0.1.tgz

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci

      - run: npm test
      - run: cd npm/doc && npm run build

      - run: npm install --no-save ./npm/doc/${{ env.PACK_FILENAME }}
      # 保存 npm pack
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACK_FILENAME }}
          path: ./npm/doc/${{ env.PACK_FILENAME }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/
      - run: npm ci

      - run: cd npm/doc && npm ci && npm run build && npm test
      - run: cd npm/doc && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
